[package]
name = "csv-txn-parser"
version = "0.1.0"
edition = "2025"

[dependencies]
csv = "1.3.1"
dashmap = "6.1.0"
rust_decimal = { version = "1.37.2", features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
