[package]
name = "csvtutor"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
dashmap = "6.1.0"
rayon = "1.10.0"
rust_decimal = { version = "1.37.2", features = ["macros"] }
serde = { version = "1.0.219", features = ["derive"] }
